name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Configuración de permisos mejorada
permissions:
  contents: read    # Permiso para leer el código
  pages: write      # Permiso para escribir en GitHub Pages
  id-token: write   # Permiso para autenticación OIDC

# Configuración de concurrencia optimizada
concurrency:
  group: "pages-${{ github.ref }}"  # Grupo por rama
  cancel-in-progress: true          # Cancela despliegues anteriores de la misma rama

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para proyectos con submodules

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build and upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Cambia esto si solo necesitas desplegar una subcarpeta
          retention-days: 1  # Reduce el tiempo de retención del artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        timeout-minutes: 5  # Límite de tiempo para el despliegue
