steps:
  - uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'
  - name: Install dependencies
    run: pip install -r requirements.txt
  - name: Run tests
    run: |
      cd /workspaces/github-portfolio
      PYTHONPATH=. pytest tests/ -v
